"""
batch-paper-summary: Literature Search Script
Search for academic papers by keyword using Semantic Scholar API.

Usage:
    # Quick search
    python search_papers.py --query "metal spinning neural operator"

    # Search + save as Markdown table
    python search_papers.py --query "deep operator network metal forming" --limit 30 --output search_results.md

    # Search by multiple keywords (OR)
    python search_papers.py --query "metal spinning; deep operator network; process parameter prediction"

    # Find related papers (given a Semantic Scholar paper ID)
    python search_papers.py --related 649def34f64ebd4a0dd9a0c4a9e50f7f0ff03474 --limit 10

Returns: title, authors, year, abstract, arXiv ID, DOI, URL, citation count.
"""

import argparse
import json
import os
import sys
import time
from datetime import datetime
from pathlib import Path
from urllib.parse import quote_plus

try:
    import requests
except ImportError:
    print("[ERROR] requests is required. Install with: pip install requests")
    sys.exit(1)


API_BASE = "https://api.semanticscholar.org/graph/v1"
SEARCH_URL = f"{API_BASE}/paper/search"
RECOMMEND_URL = f"{API_BASE}/recommendations"
BATCH_URL = f"{API_BASE}/paper/batch"

FIELDS = "title,authors,year,abstract,externalIds,url,citationCount,venue,publicationDate"


def search_papers(query: str, limit: int = 20, offset: int = 0) -> list[dict]:
    """Search Semantic Scholar by keyword."""
    params = {
        "query": query,
        "limit": min(limit, 100),
        "offset": offset,
        "fields": FIELDS,
    }
    resp = requests.get(SEARCH_URL, params=params, timeout=30)
    resp.raise_for_status()
    data = resp.json()
    return data.get("data", [])


def search_multiple_keywords(queries: list[str], limit: int = 20) -> list[dict]:
    """Search multiple keywords and merge results (deduplicated by title)."""
    all_papers = []
    seen_titles = set()
    per_query = max(1, limit // len(queries))

    for q in queries:
        q = q.strip()
        if not q:
            continue
        try:
            papers = search_papers(q, limit=per_query)
            for p in papers:
                title = p.get("title", "").lower().strip()
                if title and title not in seen_titles:
                    seen_titles.add(title)
                    all_papers.append(p)
        except Exception as e:
            print(f"  [WARN] Query '{q}' failed: {e}")
        time.sleep(1)  # rate limit

    return all_papers[:limit]


def get_related_papers(paper_id: str, limit: int = 10) -> list[dict]:
    """Get recommended papers related to a given paper."""
    url = f"{RECOMMEND_URL}/paper/{quote_plus(paper_id)}"
    params = {"limit": min(limit, 50), "fields": FIELDS}
    resp = requests.get(url, params=params, timeout=30)
    resp.raise_for_status()
    data = resp.json()
    return data.get("recommendedPapers", [])


def format_authors(authors_list: list[dict], max_authors: int = 3) -> str:
    """Format author names: 'Last, First; Last, First; et al.'"""
    if not authors_list:
        return ""
    names = [a.get("name", "") for a in authors_list if a.get("name")]
    if len(names) > max_authors:
        return "; ".join(names[:max_authors]) + " et al."
    return "; ".join(names)


def extract_id(external_ids: dict | None, key: str) -> str:
    """Safely extract an external ID."""
    if not external_ids:
        return ""
    return external_ids.get(key, "") or ""


def paper_to_markdown_row(p: dict, idx: int) -> str:
    """Format a paper dictionary as a Markdown table row."""
    title = p.get("title", "N/A")
    year = p.get("year", "")
    venue = p.get("venue", "") or ""
    authors = format_authors(p.get("authors", []))
    abstract = p.get("abstract", "") or ""
    abstract_short = abstract[:120] + "..." if len(abstract) > 120 else abstract
    citations = p.get("citationCount", 0)
    url = p.get("url", "") or ""
    arxiv_id = extract_id(p.get("externalIds"), "ArXiv")
    doi = extract_id(p.get("externalIds"), "DOI")

    links = []
    if arxiv_id:
        links.append(f"[arXiv](https://arxiv.org/abs/{arxiv_id})")
    if doi:
        links.append(f"[DOI](https://doi.org/{doi})")
    if url and not arxiv_id and not doi:
        links.append(f"[link]({url})")
    links_str = " | ".join(links) if links else "—"

    venue_str = f"*{venue}*" if venue else ""
    return f"| {idx} | {title} | {authors} | {year} | {venue_str} | {abstract_short} | {citations} | {links_str} |"


def generate_markdown_table(papers: list[dict], title: str = "Search Results") -> str:
    """Generate a full Markdown document with a results table."""
    lines = []
    lines.append(f"# {title}")
    lines.append(f"")
    lines.append(f"> Generated by Semantic Scholar API on {datetime.now().strftime('%Y-%m-%d %H:%M')} | {len(papers)} papers")
    lines.append("")
    lines.append("| # | Title | Authors | Year | Venue | Abstract | Citations | Links |")
    lines.append("|---|-------|---------|------|-------|----------|-----------|-------|")

    for i, p in enumerate(papers, start=1):
        lines.append(paper_to_markdown_row(p, i))

    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("*Report generated by batch-paper-summary/search_papers.py*")
    return "\n".join(lines)


def generate_json_output(papers: list[dict]) -> str:
    """Generate clean JSON output with only essential fields."""
    clean = []
    for p in papers:
        clean.append({
            "title": p.get("title"),
            "year": p.get("year"),
            "venue": p.get("venue"),
            "authors": [a.get("name") for a in p.get("authors", [])],
            "abstract": p.get("abstract"),
            "citationCount": p.get("citationCount"),
            "url": p.get("url"),
            "arxivId": extract_id(p.get("externalIds"), "ArXiv"),
            "doi": extract_id(p.get("externalIds"), "DOI"),
            "semanticScholarId": p.get("paperId"),
        })
    return json.dumps(clean, ensure_ascii=False, indent=2)


def main():
    parser = argparse.ArgumentParser(
        description="batch-paper-summary: Search academic papers by keyword",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python search_papers.py --query "metal spinning neural operator"
  python search_papers.py --query "deep operator network metal forming" --limit 30
  python search_papers.py --query "metal spinning; deep operator network" --output results.md
  python search_papers.py --query "旋压工艺 机器学习" --limit 15
  python search_papers.py --related <paper_id> --limit 10
        """,
    )
    parser.add_argument("-q", "--query", help="Search keyword(s). Use ';' to separate multiple queries (merged & deduplicated)")
    parser.add_argument("--related", help="Find papers related to a Semantic Scholar paper ID")
    parser.add_argument("-l", "--limit", type=int, default=20, help="Max results (default: 20)")
    parser.add_argument("-o", "--output", help="Save results to Markdown file")
    parser.add_argument("--json", action="store_true", help="Output as JSON instead of Markdown")
    parser.add_argument("--offset", type=int, default=0, help="Pagination offset")

    args = parser.parse_args()

    if not args.query and not args.related:
        parser.print_help()
        print("\n[ERROR] Provide --query or --related")
        sys.exit(1)

    print(f"[INFO] Searching...")

    papers = []
    if args.related:
        query_desc = f"Related to paper {args.related}"
        papers = get_related_papers(args.related, args.limit)
    else:
        query_desc = args.query
        if ";" in args.query:
            keywords = [k.strip() for k in args.query.split(";") if k.strip()]
            papers = search_multiple_keywords(keywords, args.limit)
        else:
            papers = search_papers(args.query, args.limit)

    print(f"[INFO] Found {len(papers)} papers")

    if not papers:
        print("[INFO] No results.")
        return

    # Output
    if args.json:
        output = generate_json_output(papers)
    else:
        output = generate_markdown_table(papers, title=f"Search: {query_desc}")

    if args.output:
        out_path = Path(args.output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(output, encoding="utf-8")
        print(f"[INFO] Saved to {out_path}")
    else:
        print(output)

    # Stats
    with_arxiv = sum(1 for p in papers if extract_id(p.get("externalIds"), "ArXiv"))
    with_doi = sum(1 for p in papers if extract_id(p.get("externalIds"), "DOI"))
    total_cites = sum(p.get("citationCount", 0) or 0 for p in papers)
    print(f"\n[INFO] Stats: {with_arxiv} with arXiv, {with_doi} with DOI, {total_cites} total citations")


if __name__ == "__main__":
    main()
